// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
	"math/bits"
)

type Module struct {
	memory []byte
	maxMem int64
	g0     v128
}

func New() *Module {
	m := new(Module)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.g0 = v128{0xef, 0xcd, 0xab, 0x89, 0x67, 0x45, 0x23, 0x01, 0x10, 0x32, 0x54, 0x76, 0x98, 0xba, 0xdc, 0xfe}
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) Xv128_load_dip896(v0 int32) v128 {
	t0 := load128(m.memory[int64(uint32(v0))+8:])
	return t0
}
func (m *Module) Xv128_load8x8_s_mwwu9f(v0 int32) v128 {
	t0 := v128_load8x8_s(load64(m.memory[int64(uint32(v0))+8:]))
	return t0
}
func (m *Module) Xv128_load8x8_u_veubbv(v0 int32) v128 {
	t0 := v128_load8x8_u(load64(m.memory[int64(uint32(v0))+8:]))
	return t0
}
func (m *Module) Xv128_load16x4_s_3pbnu7(v0 int32) v128 {
	t0 := v128_load16x4_s(load64(m.memory[int64(uint32(v0))+8:]))
	return t0
}
func (m *Module) Xv128_load16x4_u_c78f47(v0 int32) v128 {
	t0 := v128_load16x4_u(load64(m.memory[int64(uint32(v0))+8:]))
	return t0
}
func (m *Module) Xv128_load32x2_s_s4naq3(v0 int32) v128 {
	t0 := v128_load32x2_s(load64(m.memory[int64(uint32(v0))+8:]))
	return t0
}
func (m *Module) Xv128_load32x2_u_how89v(v0 int32) v128 {
	t0 := v128_load32x2_u(load64(m.memory[int64(uint32(v0))+8:]))
	return t0
}
func (m *Module) Xv128_load8_splat_jg6ein(v0 int32) v128 {
	t0 := i8x16_splat(int32(m.memory[int64(uint32(v0))+8]))
	return t0
}
func (m *Module) Xv128_load16_splat_fu6t3v(v0 int32) v128 {
	t0 := i16x8_splat(int32(load16(m.memory[int64(uint32(v0))+8:])))
	return t0
}
func (m *Module) Xv128_load32_splat_41cz0k(v0 int32) v128 {
	t0 := i32x4_splat(int32(load32(m.memory[int64(uint32(v0))+8:])))
	return t0
}
func (m *Module) Xv128_load64_splat_5cob4f(v0 int32) v128 {
	t0 := i64x2_splat(int64(load64(m.memory[int64(uint32(v0))+8:])))
	return t0
}
func (m *Module) Xv128_store_lkozsu(v0 int32, v1 v128) {
	store128(m.memory[int64(uint32(v0))+8:], v1)
}
func (m *Module) Xv128_const_t9ir8q() v128 {
	return v128{0x44, 0x33, 0x22, 0x11, 0x88, 0x77, 0x66, 0x55, 0xcc, 0xbb, 0xaa, 0x99, 0x00, 0xff, 0xee, 0xdd}
}
func (m *Module) Xi8x16_shuffle_brw309(v0, v1 v128) v128 {
	return i8x16_shuffle(v0, v1, v128{0x03, 0x0a, 0x11, 0x18, 0x1f, 0x06, 0x0d, 0x14, 0x1b, 0x02, 0x09, 0x10, 0x17, 0x1e, 0x05, 0x0c})
}
func (m *Module) Xi8x16_swizzle_5jxagq(v0, v1 v128) v128 {
	return i8x16_swizzle(v0, v1)
}
func (m *Module) Xi8x16_splat_g2nja2(v0 int32) v128 {
	return i8x16_splat(v0)
}
func (m *Module) Xi16x8_splat_igcvok(v0 int32) v128 {
	return i16x8_splat(v0)
}
func (m *Module) Xi32x4_splat_r71cha(v0 int32) v128 {
	return i32x4_splat(v0)
}
func (m *Module) Xi64x2_splat_kqp5jz(v0 int64) v128 {
	return i64x2_splat(v0)
}
func (m *Module) Xf32x4_splat_a37euu(v0 float32) v128 {
	return f32x4_splat(v0)
}
func (m *Module) Xf64x2_splat_2j5cxz(v0 float64) v128 {
	return f64x2_splat(v0)
}
func (m *Module) Xi8x16_extract_lane_s_20z60z(v0 v128) int32 {
	return i8x16_extract_lane_s(v0, 15)
}
func (m *Module) Xi8x16_extract_lane_u_cqra97(v0 v128) int32 {
	return i8x16_extract_lane_u(v0, 15)
}
func (m *Module) Xi8x16_replace_lane_ulmirt(v0 v128, v1 int32) v128 {
	return i8x16_replace_lane(v0, 15, v1)
}
func (m *Module) Xi16x8_extract_lane_s_p6l6jf(v0 v128) int32 {
	return i16x8_extract_lane_s(v0, 7)
}
func (m *Module) Xi16x8_extract_lane_u_xefhrn(v0 v128) int32 {
	return i16x8_extract_lane_u(v0, 7)
}
func (m *Module) Xi16x8_replace_lane_alubud(v0 v128, v1 int32) v128 {
	return i16x8_replace_lane(v0, 7, v1)
}
func (m *Module) Xi32x4_extract_lane_ui004g(v0 v128) int32 {
	return i32x4_extract_lane(v0, 3)
}
func (m *Module) Xi32x4_replace_lane_8x62or(v0 v128, v1 int32) v128 {
	return i32x4_replace_lane(v0, 3, v1)
}
func (m *Module) Xi64x2_extract_lane_4n1f5d(v0 v128) int64 {
	return i64x2_extract_lane(v0, 1)
}
func (m *Module) Xi64x2_replace_lane_q2ht1m(v0 v128, v1 int64) v128 {
	return i64x2_replace_lane(v0, 1, v1)
}
func (m *Module) Xf32x4_extract_lane_ganxux(v0 v128) float32 {
	return f32x4_extract_lane(v0, 3)
}
func (m *Module) Xf32x4_replace_lane_x518r6(v0 v128, v1 float32) v128 {
	return f32x4_replace_lane(v0, 3, v1)
}
func (m *Module) Xf64x2_extract_lane_ipm2d4(v0 v128) float64 {
	return f64x2_extract_lane(v0, 1)
}
func (m *Module) Xf64x2_replace_lane_1ze20z(v0 v128, v1 float64) v128 {
	return f64x2_replace_lane(v0, 1, v1)
}
func (m *Module) Xi8x16_eq_ng89y2(v0, v1 v128) v128 {
	return i8x16_eq(v0, v1)
}
func (m *Module) Xi8x16_ne_buj56z(v0, v1 v128) v128 {
	return i8x16_ne(v0, v1)
}
func (m *Module) Xi8x16_lt_s_tz7ilz(v0, v1 v128) v128 {
	return i8x16_lt_s(v0, v1)
}
func (m *Module) Xi8x16_lt_u_kpu9zz(v0, v1 v128) v128 {
	return i8x16_lt_u(v0, v1)
}
func (m *Module) Xi8x16_gt_s_wxf5ew(v0, v1 v128) v128 {
	return i8x16_gt_s(v0, v1)
}
func (m *Module) Xi8x16_gt_u_ptj7i8(v0, v1 v128) v128 {
	return i8x16_gt_u(v0, v1)
}
func (m *Module) Xi8x16_le_s_fl0c8z(v0, v1 v128) v128 {
	return i8x16_le_s(v0, v1)
}
func (m *Module) Xi8x16_le_u_871xwr(v0, v1 v128) v128 {
	return i8x16_le_u(v0, v1)
}
func (m *Module) Xi8x16_ge_s_cn3xzw(v0, v1 v128) v128 {
	return i8x16_ge_s(v0, v1)
}
func (m *Module) Xi8x16_ge_u_33o8xg(v0, v1 v128) v128 {
	return i8x16_ge_u(v0, v1)
}
func (m *Module) Xi16x8_eq_3e2t8m(v0, v1 v128) v128 {
	return i16x8_eq(v0, v1)
}
func (m *Module) Xi16x8_ne_vmsct3(v0, v1 v128) v128 {
	return i16x8_ne(v0, v1)
}
func (m *Module) Xi16x8_lt_s_846cvd(v0, v1 v128) v128 {
	return i16x8_lt_s(v0, v1)
}
func (m *Module) Xi16x8_lt_u_f5mji9(v0, v1 v128) v128 {
	return i16x8_lt_u(v0, v1)
}
func (m *Module) Xi16x8_gt_s_2xvzw6(v0, v1 v128) v128 {
	return i16x8_gt_s(v0, v1)
}
func (m *Module) Xi16x8_gt_u_c9p3mm(v0, v1 v128) v128 {
	return i16x8_gt_u(v0, v1)
}
func (m *Module) Xi16x8_le_s_kua1r1(v0, v1 v128) v128 {
	return i16x8_le_s(v0, v1)
}
func (m *Module) Xi16x8_le_u_ug5i2d(v0, v1 v128) v128 {
	return i16x8_le_u(v0, v1)
}
func (m *Module) Xi16x8_ge_s_q0966a(v0, v1 v128) v128 {
	return i16x8_ge_s(v0, v1)
}
func (m *Module) Xi16x8_ge_u_xbrpey(v0, v1 v128) v128 {
	return i16x8_ge_u(v0, v1)
}
func (m *Module) Xi32x4_eq_rar7uc(v0, v1 v128) v128 {
	return i32x4_eq(v0, v1)
}
func (m *Module) Xi32x4_ne_7v15id(v0, v1 v128) v128 {
	return i32x4_ne(v0, v1)
}
func (m *Module) Xi32x4_lt_s_znk91p(v0, v1 v128) v128 {
	return i32x4_lt_s(v0, v1)
}
func (m *Module) Xi32x4_lt_u_a3fvvp(v0, v1 v128) v128 {
	return i32x4_lt_u(v0, v1)
}
func (m *Module) Xi32x4_gt_s_5srv9u(v0, v1 v128) v128 {
	return i32x4_gt_s(v0, v1)
}
func (m *Module) Xi32x4_gt_u_dy7sai(v0, v1 v128) v128 {
	return i32x4_gt_u(v0, v1)
}
func (m *Module) Xi32x4_le_s_noxfsp(v0, v1 v128) v128 {
	return i32x4_le_s(v0, v1)
}
func (m *Module) Xi32x4_le_u_w4a6z5(v0, v1 v128) v128 {
	return i32x4_le_u(v0, v1)
}
func (m *Module) Xi32x4_ge_s_hk123q(v0, v1 v128) v128 {
	return i32x4_ge_s(v0, v1)
}
func (m *Module) Xi32x4_ge_u_s9tj4e(v0, v1 v128) v128 {
	return i32x4_ge_u(v0, v1)
}
func (m *Module) Xf32x4_eq_ohkucq(v0, v1 v128) v128 {
	return f32x4_eq(v0, v1)
}
func (m *Module) Xf32x4_ne_9kbshn(v0, v1 v128) v128 {
	return f32x4_ne(v0, v1)
}
func (m *Module) Xf32x4_lt_qzpcvt(v0, v1 v128) v128 {
	return f32x4_lt(v0, v1)
}
func (m *Module) Xf32x4_gt_jossig(v0, v1 v128) v128 {
	return f32x4_gt(v0, v1)
}
func (m *Module) Xf32x4_le_h0bo5(v0, v1 v128) v128 {
	return f32x4_le(v0, v1)
}
func (m *Module) Xf32x4_ge_bskz78(v0, v1 v128) v128 {
	return f32x4_ge(v0, v1)
}
func (m *Module) Xf64x2_eq_fumkj9(v0, v1 v128) v128 {
	return f64x2_eq(v0, v1)
}
func (m *Module) Xf64x2_ne_imv6ec(v0, v1 v128) v128 {
	return f64x2_ne(v0, v1)
}
func (m *Module) Xf64x2_lt_fy9pi(v0, v1 v128) v128 {
	return f64x2_lt(v0, v1)
}
func (m *Module) Xf64x2_gt_aqb4w7(v0, v1 v128) v128 {
	return f64x2_gt(v0, v1)
}
func (m *Module) Xf64x2_le_r67mq2(v0, v1 v128) v128 {
	return f64x2_le(v0, v1)
}
func (m *Module) Xf64x2_ge_kmvdgr(v0, v1 v128) v128 {
	return f64x2_ge(v0, v1)
}
func (m *Module) Xv128_not_mngkq1(v0 v128) v128 {
	return v128_not(v0)
}
func (m *Module) Xv128_and_8ll4d9(v0, v1 v128) v128 {
	return v128_and(v0, v1)
}
func (m *Module) Xv128_andnot_8rhav1(v0, v1 v128) v128 {
	return v128_andnot(v0, v1)
}
func (m *Module) Xv128_or_u7uap8(v0, v1 v128) v128 {
	return v128_or(v0, v1)
}
func (m *Module) Xv128_xor_ne9ajg(v0, v1 v128) v128 {
	return v128_xor(v0, v1)
}
func (m *Module) Xv128_bitselect_hqtyyh(v0, v1, v2 v128) v128 {
	return v128_bitselect(v0, v1, v2)
}
func (m *Module) Xv128_any_true_1s203v(v0 v128) int32 {
	return v128_any_true(v0)
}
func (m *Module) Xv128_load8_lane_bcsgmf(v0 int32, v1 v128) v128 {
	t0 := i8x16_replace_lane(v1, 15, int32(m.memory[int64(uint32(v0))+4]))
	return t0
}
func (m *Module) Xv128_load16_lane_fe04fe(v0 int32, v1 v128) v128 {
	t0 := i16x8_replace_lane(v1, 7, int32(load16(m.memory[int64(uint32(v0))+4:])))
	return t0
}
func (m *Module) Xv128_load32_lane_ozaljh(v0 int32, v1 v128) v128 {
	t0 := i32x4_replace_lane(v1, 3, int32(load32(m.memory[int64(uint32(v0))+4:])))
	return t0
}
func (m *Module) Xv128_load64_lane_zc6d5s(v0 int32, v1 v128) v128 {
	t0 := i64x2_replace_lane(v1, 1, int64(load64(m.memory[int64(uint32(v0))+4:])))
	return t0
}
func (m *Module) Xv128_store8_lane_jftylf(v0 int32, v1 v128) {
	m.memory[int64(uint32(v0))+4] = byte(i8x16_extract_lane_u(v1, 15))
}
func (m *Module) Xv128_store16_lane_hjllv1(v0 int32, v1 v128) {
	store16(m.memory[int64(uint32(v0))+4:], uint16(i16x8_extract_lane_u(v1, 7)))
}
func (m *Module) Xv128_store32_lane_q0rn62(v0 int32, v1 v128) {
	store32(m.memory[int64(uint32(v0))+4:], uint32(i32x4_extract_lane(v1, 3)))
}
func (m *Module) Xv128_store64_lane_x6eaw7(v0 int32, v1 v128) {
	store64(m.memory[int64(uint32(v0))+4:], uint64(i64x2_extract_lane(v1, 1)))
}
func (m *Module) Xv128_load32_zero_ugbgud(v0 int32) v128 {
	t0 := v128_load32_zero(load32(m.memory[int64(uint32(v0))+8:]))
	return t0
}
func (m *Module) Xv128_load64_zero_ku7gdk(v0 int32) v128 {
	t0 := v128_load64_zero(load64(m.memory[int64(uint32(v0))+8:]))
	return t0
}
func (m *Module) Xf32x4_demote_f64x2_zero_jndnwx(v0 v128) v128 {
	return f32x4_demote_f64x2_zero(v0)
}
func (m *Module) Xf64x2_promote_low_f32x4_aob3um(v0 v128) v128 {
	return f64x2_promote_low_f32x4(v0)
}
func (m *Module) Xi8x16_abs_8cqcxd(v0 v128) v128 {
	return i8x16_abs(v0)
}
func (m *Module) Xi8x16_neg_z6sup4(v0 v128) v128 {
	return i8x16_neg(v0)
}
func (m *Module) Xi8x16_popcnt_absced(v0 v128) v128 {
	return i8x16_popcnt(v0)
}
func (m *Module) Xi8x16_all_true_c3ne4j(v0 v128) int32 {
	return i8x16_all_true(v0)
}
func (m *Module) Xi8x16_bitmask_7mwutr(v0 v128) int32 {
	return i8x16_bitmask(v0)
}
func (m *Module) Xi8x16_narrow_i16x8_s_cc5wne(v0, v1 v128) v128 {
	return i8x16_narrow_i16x8_s(v0, v1)
}
func (m *Module) Xi8x16_narrow_i16x8_u_1wdg82(v0, v1 v128) v128 {
	return i8x16_narrow_i16x8_u(v0, v1)
}
func (m *Module) Xf32x4_ceil_q8dwfs(v0 v128) v128 {
	return f32x4_ceil(v0)
}
func (m *Module) Xf32x4_floor_d6bqww(v0 v128) v128 {
	return f32x4_floor(v0)
}
func (m *Module) Xf32x4_trunc_y7vmuz(v0 v128) v128 {
	return f32x4_trunc(v0)
}
func (m *Module) Xf32x4_nearest_hwbrbv(v0 v128) v128 {
	return f32x4_nearest(v0)
}
func (m *Module) Xi8x16_shl_nbhtuz(v0 v128, v1 int32) v128 {
	return i8x16_shl(v0, v1)
}
func (m *Module) Xi8x16_shr_s_q3qw57(v0 v128, v1 int32) v128 {
	return i8x16_shr_s(v0, v1)
}
func (m *Module) Xi8x16_shr_u_x7n8wj(v0 v128, v1 int32) v128 {
	return i8x16_shr_u(v0, v1)
}
func (m *Module) Xi8x16_add_e0hoav(v0, v1 v128) v128 {
	return i8x16_add(v0, v1)
}
func (m *Module) Xi8x16_add_sat_s_57sz3s(v0, v1 v128) v128 {
	return i8x16_add_sat_s(v0, v1)
}
func (m *Module) Xi8x16_add_sat_u_ejnsr4(v0, v1 v128) v128 {
	return i8x16_add_sat_u(v0, v1)
}
func (m *Module) Xi8x16_sub_23b8wu(v0, v1 v128) v128 {
	return i8x16_sub(v0, v1)
}
func (m *Module) Xi8x16_sub_sat_s_e5949g(v0, v1 v128) v128 {
	return i8x16_sub_sat_s(v0, v1)
}
func (m *Module) Xi8x16_sub_sat_u_5nazi4(v0, v1 v128) v128 {
	return i8x16_sub_sat_u(v0, v1)
}
func (m *Module) Xf64x2_ceil_4mcln8(v0 v128) v128 {
	return f64x2_ceil(v0)
}
func (m *Module) Xf64x2_floor_2j775(v0 v128) v128 {
	return f64x2_floor(v0)
}
func (m *Module) Xi8x16_min_s_41tyt8(v0, v1 v128) v128 {
	return i8x16_min_s(v0, v1)
}
func (m *Module) Xi8x16_min_u_b5qydw(v0, v1 v128) v128 {
	return i8x16_min_u(v0, v1)
}
func (m *Module) Xi8x16_max_s_ox1ts7(v0, v1 v128) v128 {
	return i8x16_max_s(v0, v1)
}
func (m *Module) Xi8x16_max_u_zcx3vz(v0, v1 v128) v128 {
	return i8x16_max_u(v0, v1)
}
func (m *Module) Xf64x2_trunc_n6qekq(v0 v128) v128 {
	return f64x2_trunc(v0)
}
func (m *Module) Xi8x16_avgr_u_zerym0(v0, v1 v128) v128 {
	return i8x16_avgr_u(v0, v1)
}
func (m *Module) Xi16x8_extadd_pairwise_i8x16_s_a5dspc(v0 v128) v128 {
	return i16x8_extadd_pairwise_i8x16_s(v0)
}
func (m *Module) Xi16x8_extadd_pairwise_i8x16_u_m2naw(v0 v128) v128 {
	return i16x8_extadd_pairwise_i8x16_u(v0)
}
func (m *Module) Xi32x4_extadd_pairwise_i16x8_s_mgxq5r(v0 v128) v128 {
	return i32x4_extadd_pairwise_i16x8_s(v0)
}
func (m *Module) Xi32x4_extadd_pairwise_i16x8_u_wubuiv(v0 v128) v128 {
	return i32x4_extadd_pairwise_i16x8_u(v0)
}
func (m *Module) Xi16x8_abs_fq9rk(v0 v128) v128 {
	return i16x8_abs(v0)
}
func (m *Module) Xi16x8_neg_qbk0a1(v0 v128) v128 {
	return i16x8_neg(v0)
}
func (m *Module) Xi16x8_q15mulr_sat_s_t9l95i(v0, v1 v128) v128 {
	return i16x8_q15mulr_sat_s(v0, v1)
}
func (m *Module) Xi16x8_all_true_twimfc(v0 v128) int32 {
	return i16x8_all_true(v0)
}
func (m *Module) Xi16x8_bitmask_g0mfge(v0 v128) int32 {
	return i16x8_bitmask(v0)
}
func (m *Module) Xi16x8_narrow_i32x4_s_skpbni(v0, v1 v128) v128 {
	return i16x8_narrow_i32x4_s(v0, v1)
}
func (m *Module) Xi16x8_narrow_i32x4_u_hux8t2(v0, v1 v128) v128 {
	return i16x8_narrow_i32x4_u(v0, v1)
}
func (m *Module) Xi16x8_extend_low_i8x16_s_377aho(v0 v128) v128 {
	return i16x8_extend_low_i8x16_s(v0)
}
func (m *Module) Xi16x8_extend_high_i8x16_s_giw24q(v0 v128) v128 {
	return i16x8_extend_high_i8x16_s(v0)
}
func (m *Module) Xi16x8_extend_low_i8x16_u_bp2a0k(v0 v128) v128 {
	return i16x8_extend_low_i8x16_u(v0)
}
func (m *Module) Xi16x8_extend_high_i8x16_u_79hdeq(v0 v128) v128 {
	return i16x8_extend_high_i8x16_u(v0)
}
func (m *Module) Xi16x8_shl_k4apuy(v0 v128, v1 int32) v128 {
	return i16x8_shl(v0, v1)
}
func (m *Module) Xi16x8_shr_s_9kgt8l(v0 v128, v1 int32) v128 {
	return i16x8_shr_s(v0, v1)
}
func (m *Module) Xi16x8_shr_u_1cltd9(v0 v128, v1 int32) v128 {
	return i16x8_shr_u(v0, v1)
}
func (m *Module) Xi16x8_add_bxw8jq(v0, v1 v128) v128 {
	return i16x8_add(v0, v1)
}
func (m *Module) Xi16x8_add_sat_s_k6pjoz(v0, v1 v128) v128 {
	return i16x8_add_sat_s(v0, v1)
}
func (m *Module) Xi16x8_add_sat_u_tq0aaj(v0, v1 v128) v128 {
	return i16x8_add_sat_u(v0, v1)
}
func (m *Module) Xi16x8_sub_6nwesf(v0, v1 v128) v128 {
	return i16x8_sub(v0, v1)
}
func (m *Module) Xi16x8_sub_sat_s_t0861r(v0, v1 v128) v128 {
	return i16x8_sub_sat_s(v0, v1)
}
func (m *Module) Xi16x8_sub_sat_u_kuruyf(v0, v1 v128) v128 {
	return i16x8_sub_sat_u(v0, v1)
}
func (m *Module) Xf64x2_nearest_xhwx0s(v0 v128) v128 {
	return f64x2_nearest(v0)
}
func (m *Module) Xi16x8_mul_bzslnk(v0, v1 v128) v128 {
	return i16x8_mul(v0, v1)
}
func (m *Module) Xi16x8_min_s_vhdb2a(v0, v1 v128) v128 {
	return i16x8_min_s(v0, v1)
}
func (m *Module) Xi16x8_min_u_n9iy0a(v0, v1 v128) v128 {
	return i16x8_min_u(v0, v1)
}
func (m *Module) Xi16x8_max_s_9lz22h(v0, v1 v128) v128 {
	return i16x8_max_s(v0, v1)
}
func (m *Module) Xi16x8_max_u_a11w1(v0, v1 v128) v128 {
	return i16x8_max_u(v0, v1)
}
func (m *Module) Xi16x8_avgr_u_r9696m(v0, v1 v128) v128 {
	return i16x8_avgr_u(v0, v1)
}
func (m *Module) Xi16x8_extmul_low_i8x16_s_g0m8gj(v0, v1 v128) v128 {
	return i16x8_extmul_low_i8x16_s(v0, v1)
}
func (m *Module) Xi16x8_extmul_high_i8x16_s_qy0q35(v0, v1 v128) v128 {
	return i16x8_extmul_high_i8x16_s(v0, v1)
}
func (m *Module) Xi16x8_extmul_low_i8x16_u_8mqocb(v0, v1 v128) v128 {
	return i16x8_extmul_low_i8x16_u(v0, v1)
}
func (m *Module) Xi16x8_extmul_high_i8x16_u_jwl8ft(v0, v1 v128) v128 {
	return i16x8_extmul_high_i8x16_u(v0, v1)
}
func (m *Module) Xi32x4_abs_5bessu(v0 v128) v128 {
	return i32x4_abs(v0)
}
func (m *Module) Xi32x4_neg_v6konr(v0 v128) v128 {
	return i32x4_neg(v0)
}
func (m *Module) Xi32x4_all_true_b6r91n(v0 v128) int32 {
	return i32x4_all_true(v0)
}
func (m *Module) Xi32x4_bitmask_spmrh8(v0 v128) int32 {
	return i32x4_bitmask(v0)
}
func (m *Module) Xi32x4_extend_low_i16x8_s_w4iw9m(v0 v128) v128 {
	return i32x4_extend_low_i16x8_s(v0)
}
func (m *Module) Xi32x4_extend_high_i16x8_s_j5j5n4(v0 v128) v128 {
	return i32x4_extend_high_i16x8_s(v0)
}
func (m *Module) Xi32x4_extend_low_i16x8_u_ml48c2(v0 v128) v128 {
	return i32x4_extend_low_i16x8_u(v0)
}
func (m *Module) Xi32x4_extend_high_i16x8_u_q9hkmw(v0 v128) v128 {
	return i32x4_extend_high_i16x8_u(v0)
}
func (m *Module) Xi32x4_shl_o79fx0(v0 v128, v1 int32) v128 {
	return i32x4_shl(v0, v1)
}
func (m *Module) Xi32x4_shr_s_oxq8f(v0 v128, v1 int32) v128 {
	return i32x4_shr_s(v0, v1)
}
func (m *Module) Xi32x4_shr_u_94eorr(v0 v128, v1 int32) v128 {
	return i32x4_shr_u(v0, v1)
}
func (m *Module) Xi32x4_add_gubhfc(v0, v1 v128) v128 {
	return i32x4_add(v0, v1)
}
func (m *Module) Xi32x4_sub_2p6wkh(v0, v1 v128) v128 {
	return i32x4_sub(v0, v1)
}
func (m *Module) Xi32x4_mul_gsiae6(v0, v1 v128) v128 {
	return i32x4_mul(v0, v1)
}
func (m *Module) Xi32x4_min_s_npl0zs(v0, v1 v128) v128 {
	return i32x4_min_s(v0, v1)
}
func (m *Module) Xi32x4_min_u_w519cw(v0, v1 v128) v128 {
	return i32x4_min_u(v0, v1)
}
func (m *Module) Xi32x4_max_s_ld2yb(v0, v1 v128) v128 {
	return i32x4_max_s(v0, v1)
}
func (m *Module) Xi32x4_max_u_a4oj4r(v0, v1 v128) v128 {
	return i32x4_max_u(v0, v1)
}
func (m *Module) Xi32x4_dot_i16x8_s_qxu7gp(v0, v1 v128) v128 {
	return i32x4_dot_i16x8_s(v0, v1)
}
func (m *Module) Xi32x4_extmul_low_i16x8_s_i60z85(v0, v1 v128) v128 {
	return i32x4_extmul_low_i16x8_s(v0, v1)
}
func (m *Module) Xi32x4_extmul_high_i16x8_s_7dljez(v0, v1 v128) v128 {
	return i32x4_extmul_high_i16x8_s(v0, v1)
}
func (m *Module) Xi32x4_extmul_low_i16x8_u_stf2kd(v0, v1 v128) v128 {
	return i32x4_extmul_low_i16x8_u(v0, v1)
}
func (m *Module) Xi32x4_extmul_high_i16x8_u_gph17n(v0, v1 v128) v128 {
	return i32x4_extmul_high_i16x8_u(v0, v1)
}
func (m *Module) Xi64x2_abs_7zl7zh(v0 v128) v128 {
	return i64x2_abs(v0)
}
func (m *Module) Xi64x2_neg_zdm7n8(v0 v128) v128 {
	return i64x2_neg(v0)
}
func (m *Module) Xi64x2_all_true_ls7sva(v0 v128) int32 {
	return i64x2_all_true(v0)
}
func (m *Module) Xi64x2_bitmask_n8mlkb(v0 v128) int32 {
	return i64x2_bitmask(v0)
}
func (m *Module) Xi64x2_extend_low_i32x4_s_dam2s8(v0 v128) v128 {
	return i64x2_extend_low_i32x4_s(v0)
}
func (m *Module) Xi64x2_extend_high_i32x4_s_5kfr8n(v0 v128) v128 {
	return i64x2_extend_high_i32x4_s(v0)
}
func (m *Module) Xi64x2_extend_low_i32x4_u_5wmn3k(v0 v128) v128 {
	return i64x2_extend_low_i32x4_u(v0)
}
func (m *Module) Xi64x2_extend_high_i32x4_u_e2cggf(v0 v128) v128 {
	return i64x2_extend_high_i32x4_u(v0)
}
func (m *Module) Xi64x2_shl_nohvef(v0 v128, v1 int32) v128 {
	return i64x2_shl(v0, v1)
}
func (m *Module) Xi64x2_shr_s_buxb9a(v0 v128, v1 int32) v128 {
	return i64x2_shr_s(v0, v1)
}
func (m *Module) Xi64x2_shr_u_3cyuhi(v0 v128, v1 int32) v128 {
	return i64x2_shr_u(v0, v1)
}
func (m *Module) Xi64x2_add_edmr6j(v0, v1 v128) v128 {
	return i64x2_add(v0, v1)
}
func (m *Module) Xi64x2_sub_1wfqte(v0, v1 v128) v128 {
	return i64x2_sub(v0, v1)
}
func (m *Module) Xi64x2_mul_eebhml(v0, v1 v128) v128 {
	return i64x2_mul(v0, v1)
}
func (m *Module) Xi64x2_eq_rdinf(v0, v1 v128) v128 {
	return i64x2_eq(v0, v1)
}
func (m *Module) Xi64x2_ne_yk0dtm(v0, v1 v128) v128 {
	return i64x2_ne(v0, v1)
}
func (m *Module) Xi64x2_lt_s_v70mqp(v0, v1 v128) v128 {
	return i64x2_lt_s(v0, v1)
}
func (m *Module) Xi64x2_gt_s_r9vdvi(v0, v1 v128) v128 {
	return i64x2_gt_s(v0, v1)
}
func (m *Module) Xi64x2_le_s_9xoyj9(v0, v1 v128) v128 {
	return i64x2_le_s(v0, v1)
}
func (m *Module) Xi64x2_ge_s_duiyve(v0, v1 v128) v128 {
	return i64x2_ge_s(v0, v1)
}
func (m *Module) Xi64x2_extmul_low_i32x4_s_1h979z(v0, v1 v128) v128 {
	return i64x2_extmul_low_i32x4_s(v0, v1)
}
func (m *Module) Xi64x2_extmul_high_i32x4_s_jka4jg(v0, v1 v128) v128 {
	return i64x2_extmul_high_i32x4_s(v0, v1)
}
func (m *Module) Xi64x2_extmul_low_i32x4_u_9z5ypr(v0, v1 v128) v128 {
	return i64x2_extmul_low_i32x4_u(v0, v1)
}
func (m *Module) Xi64x2_extmul_high_i32x4_u_ua391w(v0, v1 v128) v128 {
	return i64x2_extmul_high_i32x4_u(v0, v1)
}
func (m *Module) Xf32x4_abs_u12fnn(v0 v128) v128 {
	return f32x4_abs(v0)
}
func (m *Module) Xf32x4_neg_36dgm2(v0 v128) v128 {
	return f32x4_neg(v0)
}
func (m *Module) Xf32x4_sqrt_tg8jit(v0 v128) v128 {
	return f32x4_sqrt(v0)
}
func (m *Module) Xf32x4_add_hnmg6t(v0, v1 v128) v128 {
	return f32x4_add(v0, v1)
}
func (m *Module) Xf32x4_sub_vtex2k(v0, v1 v128) v128 {
	return f32x4_sub(v0, v1)
}
func (m *Module) Xf32x4_mul_hmz4wj(v0, v1 v128) v128 {
	return f32x4_mul(v0, v1)
}
func (m *Module) Xf32x4_div_ki9day(v0, v1 v128) v128 {
	return f32x4_div(v0, v1)
}
func (m *Module) Xf32x4_min_knlwg1(v0, v1 v128) v128 {
	return f32x4_min(v0, v1)
}
func (m *Module) Xf32x4_max_stdvi6(v0, v1 v128) v128 {
	return f32x4_max(v0, v1)
}
func (m *Module) Xf32x4_pmin_di05se(v0, v1 v128) v128 {
	return f32x4_pmin(v0, v1)
}
func (m *Module) Xf32x4_pmax_73867l(v0, v1 v128) v128 {
	return f32x4_pmax(v0, v1)
}
func (m *Module) Xf64x2_abs_qlhs80(v0 v128) v128 {
	return f64x2_abs(v0)
}
func (m *Module) Xf64x2_neg_5pjuh(v0 v128) v128 {
	return f64x2_neg(v0)
}
func (m *Module) Xf64x2_sqrt_7i8zeh(v0 v128) v128 {
	return f64x2_sqrt(v0)
}
func (m *Module) Xf64x2_add_laosk6(v0, v1 v128) v128 {
	return f64x2_add(v0, v1)
}
func (m *Module) Xf64x2_sub_xsjoy7(v0, v1 v128) v128 {
	return f64x2_sub(v0, v1)
}
func (m *Module) Xf64x2_mul_lcjecw(v0, v1 v128) v128 {
	return f64x2_mul(v0, v1)
}
func (m *Module) Xf64x2_div_jfimwp(v0, v1 v128) v128 {
	return f64x2_div(v0, v1)
}
func (m *Module) Xf64x2_min_i6x6ci(v0, v1 v128) v128 {
	return f64x2_min(v0, v1)
}
func (m *Module) Xf64x2_max_t25ufx(v0, v1 v128) v128 {
	return f64x2_max(v0, v1)
}
func (m *Module) Xf64x2_pmin_igoo82(v0, v1 v128) v128 {
	return f64x2_pmin(v0, v1)
}
func (m *Module) Xf64x2_pmax_sr5cwt(v0, v1 v128) v128 {
	return f64x2_pmax(v0, v1)
}
func (m *Module) Xi32x4_trunc_sat_f32x4_s_usse68(v0 v128) v128 {
	return i32x4_trunc_sat_f32x4_s(v0)
}
func (m *Module) Xi32x4_trunc_sat_f32x4_u_kfgenc(v0 v128) v128 {
	return i32x4_trunc_sat_f32x4_u(v0)
}
func (m *Module) Xf32x4_convert_i32x4_s_fbwhy(v0 v128) v128 {
	return f32x4_convert_i32x4_s(v0)
}
func (m *Module) Xf32x4_convert_i32x4_u_a1490u(v0 v128) v128 {
	return f32x4_convert_i32x4_u(v0)
}
func (m *Module) Xi32x4_trunc_sat_f64x2_s_zero_s2u9s5(v0 v128) v128 {
	return i32x4_trunc_sat_f64x2_s_zero(v0)
}
func (m *Module) Xi32x4_trunc_sat_f64x2_u_zero_3tpghd(v0 v128) v128 {
	return i32x4_trunc_sat_f64x2_u_zero(v0)
}
func (m *Module) Xf64x2_convert_low_i32x4_s_76ywkm(v0 v128) v128 {
	return f64x2_convert_low_i32x4_s(v0)
}
func (m *Module) Xf64x2_convert_low_i32x4_u_ggen4e(v0 v128) v128 {
	return f64x2_convert_low_i32x4_u(v0)
}
func (m *Module) Xplumbing(v0 v128) v128 {
	var v1 v128
	t0 := m.g0
	v1 = t0
	var p1 v128
	p1 = v128_xor(v0, v1)
	m.g0 = p1
	t2 := m.g0
	return t2
}
func (m *Module) Xsum16(v0 int32) int32 {
	var v1 v128
	v1 = i32x4_extadd_pairwise_i16x8_u(i16x8_extadd_pairwise_i8x16_u(i8x16_splat(v0)))
	return i32x4_extract_lane(v1, 0) + i32x4_extract_lane(v1, 1) + (i32x4_extract_lane(v1, 2) + i32x4_extract_lane(v1, 3))
}
func (m *Module) Xaddsat(v0, v1 int32) int32 {
	return i8x16_extract_lane_s(i8x16_add_sat_s(i8x16_splat(v0), i8x16_splat(v1)), 9)
}
func (m *Module) Xmulf(v0, v1 float32) float32 {
	return f32x4_extract_lane(f32x4_mul(f32x4_splat(v0), f32x4_splat(v1)), 2)
}
func (m *Module) Xmemrt(v0 int32) int32 {
	store128(m.memory[uint32(i32(16)):], i32x4_splat(v0))
	t0 := load128(m.memory[uint32(i32(16)):])
	return i32x4_bitmask(t0)
}
func (m *Module) Xmem() Memory {
	return (*wasmMemory)(&m.memory)
}

// The Wasm v128 type: 16 bytes, lanes stored little-endian,
// matching linear memory representation.
type v128 [16]byte

//go:nosplit
func load128(b []byte) v128 {
	return v128(b)
}

//go:nosplit
func store128(b []byte, v v128) {
	copy(b[:16], v[:])
}

//go:nosplit
func v128_load8x8_s(x uint64) (r v128) {
	for i := 0; i < 8; i++ {
		binary.LittleEndian.PutUint16(r[2*i:], uint16(int16(int8(x>>(8*i)))))
	}
	return
}

//go:nosplit
func v128_load8x8_u(x uint64) (r v128) {
	for i := 0; i < 8; i++ {
		binary.LittleEndian.PutUint16(r[2*i:], uint16(byte(x>>(8*i))))
	}
	return
}

//go:nosplit
func v128_load16x4_s(x uint64) (r v128) {
	for i := 0; i < 4; i++ {
		binary.LittleEndian.PutUint32(r[4*i:], uint32(int32(int16(x>>(16*i)))))
	}
	return
}

//go:nosplit
func v128_load16x4_u(x uint64) (r v128) {
	for i := 0; i < 4; i++ {
		binary.LittleEndian.PutUint32(r[4*i:], uint32(uint16(x>>(16*i))))
	}
	return
}

//go:nosplit
func v128_load32x2_s(x uint64) (r v128) {
	for i := 0; i < 2; i++ {
		binary.LittleEndian.PutUint64(r[8*i:], uint64(int64(int32(x>>(32*i)))))
	}
	return
}

//go:nosplit
func v128_load32x2_u(x uint64) (r v128) {
	for i := 0; i < 2; i++ {
		binary.LittleEndian.PutUint64(r[8*i:], uint64(uint32(x>>(32*i))))
	}
	return
}

//go:nosplit
func v128_load32_zero(x uint32) (r v128) {
	binary.LittleEndian.PutUint32(r[0:], x)
	return
}

//go:nosplit
func v128_load64_zero(x uint64) (r v128) {
	binary.LittleEndian.PutUint64(r[0:], x)
	return
}

//go:nosplit
func i8x16_splat(x int32) (r v128) {
	for i := range r {
		r[i] = byte(x)
	}
	return
}

//go:nosplit
func i16x8_splat(x int32) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], uint16(x))
	}
	return
}

//go:nosplit
func i32x4_splat(x int32) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], uint32(x))
	}
	return
}

//go:nosplit
func i64x2_splat(x int64) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], uint64(x))
	}
	return
}

//go:nosplit
func f32x4_splat(x float32) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(x))
	}
	return
}

//go:nosplit
func f64x2_splat(x float64) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(x))
	}
	return
}

//go:nosplit
func i8x16_shuffle(a, b, m v128) (r v128) {
	for i := range r {
		if j := m[i]; j < 16 {
			r[i] = a[j]
		} else {
			r[i] = b[j-16]
		}
	}
	return
}

//go:nosplit
func i8x16_swizzle(a, s v128) (r v128) {
	for i := range r {
		if j := s[i]; j < 16 {
			r[i] = a[j]
		}
	}
	return
}

//go:nosplit
func i8x16_extract_lane_s(v v128, l int) int32 {
	return int32(int8(v[l]))
}

//go:nosplit
func i8x16_extract_lane_u(v v128, l int) int32 {
	return int32(v[l])
}

//go:nosplit
func i8x16_replace_lane(v v128, l int, x int32) v128 {
	v[l] = byte(x)
	return v
}

//go:nosplit
func i16x8_extract_lane_s(v v128, l int) int32 {
	return int32(int16(binary.LittleEndian.Uint16(v[2*l:])))
}

//go:nosplit
func i16x8_extract_lane_u(v v128, l int) int32 {
	return int32(binary.LittleEndian.Uint16(v[2*l:]))
}

//go:nosplit
func i16x8_replace_lane(v v128, l int, x int32) v128 {
	binary.LittleEndian.PutUint16(v[2*l:], uint16(x))
	return v
}

//go:nosplit
func i32x4_extract_lane(v v128, l int) int32 {
	return int32(binary.LittleEndian.Uint32(v[4*l:]))
}

//go:nosplit
func i32x4_replace_lane(v v128, l int, x int32) v128 {
	binary.LittleEndian.PutUint32(v[4*l:], uint32(x))
	return v
}

//go:nosplit
func i64x2_extract_lane(v v128, l int) int64 {
	return int64(binary.LittleEndian.Uint64(v[8*l:]))
}

//go:nosplit
func i64x2_replace_lane(v v128, l int, x int64) v128 {
	binary.LittleEndian.PutUint64(v[8*l:], uint64(x))
	return v
}

//go:nosplit
func f32x4_extract_lane(v v128, l int) float32 {
	return math.Float32frombits(binary.LittleEndian.Uint32(v[4*l:]))
}

//go:nosplit
func f32x4_replace_lane(v v128, l int, x float32) v128 {
	binary.LittleEndian.PutUint32(v[4*l:], math.Float32bits(x))
	return v
}

//go:nosplit
func f64x2_extract_lane(v v128, l int) float64 {
	return math.Float64frombits(binary.LittleEndian.Uint64(v[8*l:]))
}

//go:nosplit
func f64x2_replace_lane(v v128, l int, x float64) v128 {
	binary.LittleEndian.PutUint64(v[8*l:], math.Float64bits(x))
	return v
}

//go:nosplit
func v128_not(a v128) (r v128) {
	for i := range r {
		r[i] = ^a[i]
	}
	return
}

//go:nosplit
func v128_and(a, b v128) (r v128) {
	for i := range r {
		r[i] = a[i] & b[i]
	}
	return
}

//go:nosplit
func v128_andnot(a, b v128) (r v128) {
	for i := range r {
		r[i] = a[i] &^ b[i]
	}
	return
}

//go:nosplit
func v128_or(a, b v128) (r v128) {
	for i := range r {
		r[i] = a[i] | b[i]
	}
	return
}

//go:nosplit
func v128_xor(a, b v128) (r v128) {
	for i := range r {
		r[i] = a[i] ^ b[i]
	}
	return
}

//go:nosplit
func v128_bitselect(a, b, c v128) (r v128) {
	for i := range r {
		r[i] = a[i]&c[i] | b[i]&^c[i]
	}
	return
}

//go:nosplit
func v128_any_true(v v128) int32 {
	var zero v128
	if v != zero {
		return 1
	}
	return 0
}

//go:nosplit
func i8x16_all_true(v v128) int32 {
	for i := range v {
		if v[i] == 0 {
			return 0
		}
	}
	return 1
}

//go:nosplit
func i16x8_all_true(v v128) int32 {
	for i := 0; i < 16; i += 2 {
		if binary.LittleEndian.Uint16(v[i:]) == 0 {
			return 0
		}
	}
	return 1
}

//go:nosplit
func i32x4_all_true(v v128) int32 {
	for i := 0; i < 16; i += 4 {
		if binary.LittleEndian.Uint32(v[i:]) == 0 {
			return 0
		}
	}
	return 1
}

//go:nosplit
func i64x2_all_true(v v128) int32 {
	for i := 0; i < 16; i += 8 {
		if binary.LittleEndian.Uint64(v[i:]) == 0 {
			return 0
		}
	}
	return 1
}

//go:nosplit
func i8x16_bitmask(v v128) int32 {
	// SWAR movemask: gather each byte's MSB into one bit per lane.
	const msb = 0x8080808080808080
	const mul = 0x0102040810204080
	lo := binary.LittleEndian.Uint64(v[0:8]) & msb >> 7 * mul >> 56
	hi := binary.LittleEndian.Uint64(v[8:16]) & msb >> 7 * mul >> 56
	return int32(hi<<8 | lo)
}

//go:nosplit
func i16x8_bitmask(v v128) (r int32) {
	for i := 0; i < 8; i++ {
		r |= int32(binary.LittleEndian.Uint16(v[2*i:])>>15) << i
	}
	return
}

//go:nosplit
func i32x4_bitmask(v v128) (r int32) {
	for i := 0; i < 4; i++ {
		r |= int32(binary.LittleEndian.Uint32(v[4*i:])>>31) << i
	}
	return
}

//go:nosplit
func i64x2_bitmask(v v128) (r int32) {
	for i := 0; i < 2; i++ {
		r |= int32(binary.LittleEndian.Uint64(v[8*i:])>>63) << i
	}
	return
}

//go:nosplit
func i8x16_eq(a, b v128) (r v128) {
	for i := range r {
		if a[i] == b[i] {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i8x16_ne(a, b v128) (r v128) {
	for i := range r {
		if a[i] != b[i] {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i8x16_lt_s(a, b v128) (r v128) {
	for i := range r {
		if int8(a[i]) < int8(b[i]) {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i8x16_lt_u(a, b v128) (r v128) {
	for i := range r {
		if a[i] < b[i] {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i8x16_gt_s(a, b v128) (r v128) {
	for i := range r {
		if int8(a[i]) > int8(b[i]) {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i8x16_gt_u(a, b v128) (r v128) {
	for i := range r {
		if a[i] > b[i] {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i8x16_le_s(a, b v128) (r v128) {
	for i := range r {
		if int8(a[i]) <= int8(b[i]) {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i8x16_le_u(a, b v128) (r v128) {
	for i := range r {
		if a[i] <= b[i] {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i8x16_ge_s(a, b v128) (r v128) {
	for i := range r {
		if int8(a[i]) >= int8(b[i]) {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i8x16_ge_u(a, b v128) (r v128) {
	for i := range r {
		if a[i] >= b[i] {
			r[i] = 0xff
		}
	}
	return
}

//go:nosplit
func i16x8_eq(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if binary.LittleEndian.Uint16(a[i:]) == binary.LittleEndian.Uint16(b[i:]) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i16x8_ne(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if binary.LittleEndian.Uint16(a[i:]) != binary.LittleEndian.Uint16(b[i:]) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i16x8_lt_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if int16(binary.LittleEndian.Uint16(a[i:])) < int16(binary.LittleEndian.Uint16(b[i:])) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i16x8_lt_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if binary.LittleEndian.Uint16(a[i:]) < binary.LittleEndian.Uint16(b[i:]) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i16x8_gt_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if int16(binary.LittleEndian.Uint16(a[i:])) > int16(binary.LittleEndian.Uint16(b[i:])) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i16x8_gt_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if binary.LittleEndian.Uint16(a[i:]) > binary.LittleEndian.Uint16(b[i:]) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i16x8_le_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if int16(binary.LittleEndian.Uint16(a[i:])) <= int16(binary.LittleEndian.Uint16(b[i:])) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i16x8_le_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if binary.LittleEndian.Uint16(a[i:]) <= binary.LittleEndian.Uint16(b[i:]) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i16x8_ge_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if int16(binary.LittleEndian.Uint16(a[i:])) >= int16(binary.LittleEndian.Uint16(b[i:])) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i16x8_ge_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		if binary.LittleEndian.Uint16(a[i:]) >= binary.LittleEndian.Uint16(b[i:]) {
			binary.LittleEndian.PutUint16(r[i:], 0xffff)
		}
	}
	return
}

//go:nosplit
func i32x4_eq(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if binary.LittleEndian.Uint32(a[i:]) == binary.LittleEndian.Uint32(b[i:]) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i32x4_ne(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if binary.LittleEndian.Uint32(a[i:]) != binary.LittleEndian.Uint32(b[i:]) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i32x4_lt_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if int32(binary.LittleEndian.Uint32(a[i:])) < int32(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i32x4_lt_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if binary.LittleEndian.Uint32(a[i:]) < binary.LittleEndian.Uint32(b[i:]) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i32x4_gt_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if int32(binary.LittleEndian.Uint32(a[i:])) > int32(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i32x4_gt_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if binary.LittleEndian.Uint32(a[i:]) > binary.LittleEndian.Uint32(b[i:]) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i32x4_le_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if int32(binary.LittleEndian.Uint32(a[i:])) <= int32(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i32x4_le_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if binary.LittleEndian.Uint32(a[i:]) <= binary.LittleEndian.Uint32(b[i:]) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i32x4_ge_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if int32(binary.LittleEndian.Uint32(a[i:])) >= int32(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i32x4_ge_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if binary.LittleEndian.Uint32(a[i:]) >= binary.LittleEndian.Uint32(b[i:]) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func i64x2_eq(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if binary.LittleEndian.Uint64(a[i:]) == binary.LittleEndian.Uint64(b[i:]) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func i64x2_ne(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if binary.LittleEndian.Uint64(a[i:]) != binary.LittleEndian.Uint64(b[i:]) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func i64x2_lt_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if int64(binary.LittleEndian.Uint64(a[i:])) < int64(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func i64x2_gt_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if int64(binary.LittleEndian.Uint64(a[i:])) > int64(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func i64x2_le_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if int64(binary.LittleEndian.Uint64(a[i:])) <= int64(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func i64x2_ge_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if int64(binary.LittleEndian.Uint64(a[i:])) >= int64(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func f32x4_eq(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if math.Float32frombits(binary.LittleEndian.Uint32(a[i:])) == math.Float32frombits(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func f32x4_ne(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if math.Float32frombits(binary.LittleEndian.Uint32(a[i:])) != math.Float32frombits(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func f32x4_lt(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if math.Float32frombits(binary.LittleEndian.Uint32(a[i:])) < math.Float32frombits(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func f32x4_gt(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if math.Float32frombits(binary.LittleEndian.Uint32(a[i:])) > math.Float32frombits(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func f32x4_le(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if math.Float32frombits(binary.LittleEndian.Uint32(a[i:])) <= math.Float32frombits(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func f32x4_ge(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		if math.Float32frombits(binary.LittleEndian.Uint32(a[i:])) >= math.Float32frombits(binary.LittleEndian.Uint32(b[i:])) {
			binary.LittleEndian.PutUint32(r[i:], 0xffffffff)
		}
	}
	return
}

//go:nosplit
func f64x2_eq(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if math.Float64frombits(binary.LittleEndian.Uint64(a[i:])) == math.Float64frombits(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func f64x2_ne(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if math.Float64frombits(binary.LittleEndian.Uint64(a[i:])) != math.Float64frombits(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func f64x2_lt(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if math.Float64frombits(binary.LittleEndian.Uint64(a[i:])) < math.Float64frombits(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func f64x2_gt(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if math.Float64frombits(binary.LittleEndian.Uint64(a[i:])) > math.Float64frombits(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func f64x2_le(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if math.Float64frombits(binary.LittleEndian.Uint64(a[i:])) <= math.Float64frombits(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func f64x2_ge(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		if math.Float64frombits(binary.LittleEndian.Uint64(a[i:])) >= math.Float64frombits(binary.LittleEndian.Uint64(b[i:])) {
			binary.LittleEndian.PutUint64(r[i:], 0xffffffffffffffff)
		}
	}
	return
}

//go:nosplit
func i8x16_abs(a v128) (r v128) {
	for i := range r {
		x := int8(a[i])
		if x < 0 {
			x = -x
		}
		r[i] = byte(x)
	}
	return
}

//go:nosplit
func i8x16_neg(a v128) (r v128) {
	for i := range r {
		r[i] = byte(-int8(a[i]))
	}
	return
}

//go:nosplit
func i8x16_popcnt(a v128) (r v128) {
	for i := range r {
		r[i] = byte(bits.OnesCount8(a[i]))
	}
	return
}

//go:nosplit
func i16x8_abs(a v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int16(binary.LittleEndian.Uint16(a[i:]))
		if x < 0 {
			x = -x
		}
		binary.LittleEndian.PutUint16(r[i:], uint16(x))
	}
	return
}

//go:nosplit
func i16x8_neg(a v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], uint16(-int16(binary.LittleEndian.Uint16(a[i:]))))
	}
	return
}

//go:nosplit
func i32x4_abs(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := int32(binary.LittleEndian.Uint32(a[i:]))
		if x < 0 {
			x = -x
		}
		binary.LittleEndian.PutUint32(r[i:], uint32(x))
	}
	return
}

//go:nosplit
func i32x4_neg(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], uint32(-int32(binary.LittleEndian.Uint32(a[i:]))))
	}
	return
}

//go:nosplit
func i64x2_abs(a v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := int64(binary.LittleEndian.Uint64(a[i:]))
		if x < 0 {
			x = -x
		}
		binary.LittleEndian.PutUint64(r[i:], uint64(x))
	}
	return
}

//go:nosplit
func i64x2_neg(a v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], uint64(-int64(binary.LittleEndian.Uint64(a[i:]))))
	}
	return
}

//go:nosplit
func i8x16_shl(a v128, y int32) (r v128) {
	for i := range r {
		r[i] = a[i] << (y & 7)
	}
	return
}

//go:nosplit
func i8x16_shr_s(a v128, y int32) (r v128) {
	for i := range r {
		r[i] = byte(int8(a[i]) >> (y & 7))
	}
	return
}

//go:nosplit
func i8x16_shr_u(a v128, y int32) (r v128) {
	for i := range r {
		r[i] = a[i] >> (y & 7)
	}
	return
}

//go:nosplit
func i16x8_shl(a v128, y int32) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], binary.LittleEndian.Uint16(a[i:])<<(y&15))
	}
	return
}

//go:nosplit
func i16x8_shr_s(a v128, y int32) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], uint16(int16(binary.LittleEndian.Uint16(a[i:]))>>(y&15)))
	}
	return
}

//go:nosplit
func i16x8_shr_u(a v128, y int32) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], binary.LittleEndian.Uint16(a[i:])>>(y&15))
	}
	return
}

//go:nosplit
func i32x4_shl(a v128, y int32) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], binary.LittleEndian.Uint32(a[i:])<<(y&31))
	}
	return
}

//go:nosplit
func i32x4_shr_s(a v128, y int32) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], uint32(int32(binary.LittleEndian.Uint32(a[i:]))>>(y&31)))
	}
	return
}

//go:nosplit
func i32x4_shr_u(a v128, y int32) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], binary.LittleEndian.Uint32(a[i:])>>(y&31))
	}
	return
}

//go:nosplit
func i64x2_shl(a v128, y int32) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], binary.LittleEndian.Uint64(a[i:])<<(y&63))
	}
	return
}

//go:nosplit
func i64x2_shr_s(a v128, y int32) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], uint64(int64(binary.LittleEndian.Uint64(a[i:]))>>(y&63)))
	}
	return
}

//go:nosplit
func i64x2_shr_u(a v128, y int32) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], binary.LittleEndian.Uint64(a[i:])>>(y&63))
	}
	return
}

//go:nosplit
func i8x16_add(a, b v128) (r v128) {
	for i := range r {
		r[i] = a[i] + b[i]
	}
	return
}

//go:nosplit
func i8x16_sub(a, b v128) (r v128) {
	for i := range r {
		r[i] = a[i] - b[i]
	}
	return
}

//go:nosplit
func i8x16_add_sat_s(a, b v128) (r v128) {
	for i := range r {
		x := int32(int8(a[i])) + int32(int8(b[i]))
		if x < math.MinInt8 {
			x = math.MinInt8
		}
		if x > math.MaxInt8 {
			x = math.MaxInt8
		}
		r[i] = byte(x)
	}
	return
}

//go:nosplit
func i8x16_add_sat_u(a, b v128) (r v128) {
	for i := range r {
		x := int32(a[i]) + int32(b[i])
		if x > math.MaxUint8 {
			x = math.MaxUint8
		}
		r[i] = byte(x)
	}
	return
}

//go:nosplit
func i8x16_sub_sat_s(a, b v128) (r v128) {
	for i := range r {
		x := int32(int8(a[i])) - int32(int8(b[i]))
		if x < math.MinInt8 {
			x = math.MinInt8
		}
		if x > math.MaxInt8 {
			x = math.MaxInt8
		}
		r[i] = byte(x)
	}
	return
}

//go:nosplit
func i8x16_sub_sat_u(a, b v128) (r v128) {
	for i := range r {
		if a[i] > b[i] {
			r[i] = a[i] - b[i]
		}
	}
	return
}

//go:nosplit
func i8x16_min_s(a, b v128) (r v128) {
	for i := range r {
		if int8(a[i]) < int8(b[i]) {
			r[i] = a[i]
		} else {
			r[i] = b[i]
		}
	}
	return
}

//go:nosplit
func i8x16_min_u(a, b v128) (r v128) {
	for i := range r {
		r[i] = min(a[i], b[i])
	}
	return
}

//go:nosplit
func i8x16_max_s(a, b v128) (r v128) {
	for i := range r {
		if int8(a[i]) > int8(b[i]) {
			r[i] = a[i]
		} else {
			r[i] = b[i]
		}
	}
	return
}

//go:nosplit
func i8x16_max_u(a, b v128) (r v128) {
	for i := range r {
		r[i] = max(a[i], b[i])
	}
	return
}

//go:nosplit
func i8x16_avgr_u(a, b v128) (r v128) {
	for i := range r {
		r[i] = byte((int32(a[i]) + int32(b[i]) + 1) / 2)
	}
	return
}

//go:nosplit
func i16x8_add(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], binary.LittleEndian.Uint16(a[i:])+binary.LittleEndian.Uint16(b[i:]))
	}
	return
}

//go:nosplit
func i16x8_sub(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], binary.LittleEndian.Uint16(a[i:])-binary.LittleEndian.Uint16(b[i:]))
	}
	return
}

//go:nosplit
func i16x8_mul(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], binary.LittleEndian.Uint16(a[i:])*binary.LittleEndian.Uint16(b[i:]))
	}
	return
}

//go:nosplit
func i16x8_add_sat_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int32(int16(binary.LittleEndian.Uint16(a[i:]))) + int32(int16(binary.LittleEndian.Uint16(b[i:])))
		if x < math.MinInt16 {
			x = math.MinInt16
		}
		if x > math.MaxInt16 {
			x = math.MaxInt16
		}
		binary.LittleEndian.PutUint16(r[i:], uint16(x))
	}
	return
}

//go:nosplit
func i16x8_add_sat_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int32(binary.LittleEndian.Uint16(a[i:])) + int32(binary.LittleEndian.Uint16(b[i:]))
		if x > math.MaxUint16 {
			x = math.MaxUint16
		}
		binary.LittleEndian.PutUint16(r[i:], uint16(x))
	}
	return
}

//go:nosplit
func i16x8_sub_sat_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int32(int16(binary.LittleEndian.Uint16(a[i:]))) - int32(int16(binary.LittleEndian.Uint16(b[i:])))
		if x < math.MinInt16 {
			x = math.MinInt16
		}
		if x > math.MaxInt16 {
			x = math.MaxInt16
		}
		binary.LittleEndian.PutUint16(r[i:], uint16(x))
	}
	return
}

//go:nosplit
func i16x8_sub_sat_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := binary.LittleEndian.Uint16(a[i:])
		y := binary.LittleEndian.Uint16(b[i:])
		if x > y {
			binary.LittleEndian.PutUint16(r[i:], x-y)
		}
	}
	return
}

//go:nosplit
func i16x8_min_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int16(binary.LittleEndian.Uint16(a[i:]))
		y := int16(binary.LittleEndian.Uint16(b[i:]))
		binary.LittleEndian.PutUint16(r[i:], uint16(min(x, y)))
	}
	return
}

//go:nosplit
func i16x8_min_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], min(binary.LittleEndian.Uint16(a[i:]), binary.LittleEndian.Uint16(b[i:])))
	}
	return
}

//go:nosplit
func i16x8_max_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int16(binary.LittleEndian.Uint16(a[i:]))
		y := int16(binary.LittleEndian.Uint16(b[i:]))
		binary.LittleEndian.PutUint16(r[i:], uint16(max(x, y)))
	}
	return
}

//go:nosplit
func i16x8_max_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		binary.LittleEndian.PutUint16(r[i:], max(binary.LittleEndian.Uint16(a[i:]), binary.LittleEndian.Uint16(b[i:])))
	}
	return
}

//go:nosplit
func i16x8_avgr_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int32(binary.LittleEndian.Uint16(a[i:])) + int32(binary.LittleEndian.Uint16(b[i:])) + 1
		binary.LittleEndian.PutUint16(r[i:], uint16(x/2))
	}
	return
}

//go:nosplit
func i16x8_q15mulr_sat_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int32(int16(binary.LittleEndian.Uint16(a[i:])))
		y := int32(int16(binary.LittleEndian.Uint16(b[i:])))
		p := (x*y + 0x4000) >> 15
		if p > math.MaxInt16 {
			p = math.MaxInt16
		}
		binary.LittleEndian.PutUint16(r[i:], uint16(p))
	}
	return
}

//go:nosplit
func i32x4_add(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], binary.LittleEndian.Uint32(a[i:])+binary.LittleEndian.Uint32(b[i:]))
	}
	return
}

//go:nosplit
func i32x4_sub(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], binary.LittleEndian.Uint32(a[i:])-binary.LittleEndian.Uint32(b[i:]))
	}
	return
}

//go:nosplit
func i32x4_mul(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], binary.LittleEndian.Uint32(a[i:])*binary.LittleEndian.Uint32(b[i:]))
	}
	return
}

//go:nosplit
func i32x4_min_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := int32(binary.LittleEndian.Uint32(a[i:]))
		y := int32(binary.LittleEndian.Uint32(b[i:]))
		binary.LittleEndian.PutUint32(r[i:], uint32(min(x, y)))
	}
	return
}

//go:nosplit
func i32x4_min_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], min(binary.LittleEndian.Uint32(a[i:]), binary.LittleEndian.Uint32(b[i:])))
	}
	return
}

//go:nosplit
func i32x4_max_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := int32(binary.LittleEndian.Uint32(a[i:]))
		y := int32(binary.LittleEndian.Uint32(b[i:]))
		binary.LittleEndian.PutUint32(r[i:], uint32(max(x, y)))
	}
	return
}

//go:nosplit
func i32x4_max_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], max(binary.LittleEndian.Uint32(a[i:]), binary.LittleEndian.Uint32(b[i:])))
	}
	return
}

//go:nosplit
func i32x4_dot_i16x8_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x0 := int32(int16(binary.LittleEndian.Uint16(a[i:])))
		y0 := int32(int16(binary.LittleEndian.Uint16(b[i:])))
		x1 := int32(int16(binary.LittleEndian.Uint16(a[i+2:])))
		y1 := int32(int16(binary.LittleEndian.Uint16(b[i+2:])))
		binary.LittleEndian.PutUint32(r[i:], uint32(x0*y0+x1*y1))
	}
	return
}

//go:nosplit
func i64x2_add(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], binary.LittleEndian.Uint64(a[i:])+binary.LittleEndian.Uint64(b[i:]))
	}
	return
}

//go:nosplit
func i64x2_sub(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], binary.LittleEndian.Uint64(a[i:])-binary.LittleEndian.Uint64(b[i:]))
	}
	return
}

//go:nosplit
func i64x2_mul(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], binary.LittleEndian.Uint64(a[i:])*binary.LittleEndian.Uint64(b[i:]))
	}
	return
}

//go:nosplit
func i8x16_narrow_i16x8_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int16(binary.LittleEndian.Uint16(a[i:]))
		if x < math.MinInt8 {
			x = math.MinInt8
		}
		if x > math.MaxInt8 {
			x = math.MaxInt8
		}
		r[i/2] = byte(x)
		x = int16(binary.LittleEndian.Uint16(b[i:]))
		if x < math.MinInt8 {
			x = math.MinInt8
		}
		if x > math.MaxInt8 {
			x = math.MaxInt8
		}
		r[8+i/2] = byte(x)
	}
	return
}

//go:nosplit
func i8x16_narrow_i16x8_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 2 {
		x := int16(binary.LittleEndian.Uint16(a[i:]))
		if x < 0 {
			x = 0
		}
		if x > math.MaxUint8 {
			x = math.MaxUint8
		}
		r[i/2] = byte(x)
		x = int16(binary.LittleEndian.Uint16(b[i:]))
		if x < 0 {
			x = 0
		}
		if x > math.MaxUint8 {
			x = math.MaxUint8
		}
		r[8+i/2] = byte(x)
	}
	return
}

//go:nosplit
func i16x8_narrow_i32x4_s(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := int32(binary.LittleEndian.Uint32(a[i:]))
		if x < math.MinInt16 {
			x = math.MinInt16
		}
		if x > math.MaxInt16 {
			x = math.MaxInt16
		}
		binary.LittleEndian.PutUint16(r[i/2:], uint16(x))
		x = int32(binary.LittleEndian.Uint32(b[i:]))
		if x < math.MinInt16 {
			x = math.MinInt16
		}
		if x > math.MaxInt16 {
			x = math.MaxInt16
		}
		binary.LittleEndian.PutUint16(r[8+i/2:], uint16(x))
	}
	return
}

//go:nosplit
func i16x8_narrow_i32x4_u(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := int32(binary.LittleEndian.Uint32(a[i:]))
		if x < 0 {
			x = 0
		}
		if x > math.MaxUint16 {
			x = math.MaxUint16
		}
		binary.LittleEndian.PutUint16(r[i/2:], uint16(x))
		x = int32(binary.LittleEndian.Uint32(b[i:]))
		if x < 0 {
			x = 0
		}
		if x > math.MaxUint16 {
			x = math.MaxUint16
		}
		binary.LittleEndian.PutUint16(r[8+i/2:], uint16(x))
	}
	return
}

//go:nosplit
func i16x8_extend_low_i8x16_s(a v128) (r v128) {
	for i := 0; i < 8; i++ {
		binary.LittleEndian.PutUint16(r[2*i:], uint16(int16(int8(a[i]))))
	}
	return
}

//go:nosplit
func i16x8_extend_high_i8x16_s(a v128) (r v128) {
	for i := 0; i < 8; i++ {
		binary.LittleEndian.PutUint16(r[2*i:], uint16(int16(int8(a[8+i]))))
	}
	return
}

//go:nosplit
func i16x8_extend_low_i8x16_u(a v128) (r v128) {
	for i := 0; i < 8; i++ {
		binary.LittleEndian.PutUint16(r[2*i:], uint16(a[i]))
	}
	return
}

//go:nosplit
func i16x8_extend_high_i8x16_u(a v128) (r v128) {
	for i := 0; i < 8; i++ {
		binary.LittleEndian.PutUint16(r[2*i:], uint16(a[8+i]))
	}
	return
}

//go:nosplit
func i32x4_extend_low_i16x8_s(a v128) (r v128) {
	for i := 0; i < 4; i++ {
		binary.LittleEndian.PutUint32(r[4*i:], uint32(int32(int16(binary.LittleEndian.Uint16(a[2*i:])))))
	}
	return
}

//go:nosplit
func i32x4_extend_high_i16x8_s(a v128) (r v128) {
	for i := 0; i < 4; i++ {
		binary.LittleEndian.PutUint32(r[4*i:], uint32(int32(int16(binary.LittleEndian.Uint16(a[8+2*i:])))))
	}
	return
}

//go:nosplit
func i32x4_extend_low_i16x8_u(a v128) (r v128) {
	for i := 0; i < 4; i++ {
		binary.LittleEndian.PutUint32(r[4*i:], uint32(binary.LittleEndian.Uint16(a[2*i:])))
	}
	return
}

//go:nosplit
func i32x4_extend_high_i16x8_u(a v128) (r v128) {
	for i := 0; i < 4; i++ {
		binary.LittleEndian.PutUint32(r[4*i:], uint32(binary.LittleEndian.Uint16(a[8+2*i:])))
	}
	return
}

//go:nosplit
func i64x2_extend_low_i32x4_s(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		binary.LittleEndian.PutUint64(r[8*i:], uint64(int64(int32(binary.LittleEndian.Uint32(a[4*i:])))))
	}
	return
}

//go:nosplit
func i64x2_extend_high_i32x4_s(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		binary.LittleEndian.PutUint64(r[8*i:], uint64(int64(int32(binary.LittleEndian.Uint32(a[8+4*i:])))))
	}
	return
}

//go:nosplit
func i64x2_extend_low_i32x4_u(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		binary.LittleEndian.PutUint64(r[8*i:], uint64(binary.LittleEndian.Uint32(a[4*i:])))
	}
	return
}

//go:nosplit
func i64x2_extend_high_i32x4_u(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		binary.LittleEndian.PutUint64(r[8*i:], uint64(binary.LittleEndian.Uint32(a[8+4*i:])))
	}
	return
}

//go:nosplit
func i16x8_extadd_pairwise_i8x16_s(a v128) (r v128) {
	for i := 0; i < 8; i++ {
		x := int16(int8(a[2*i])) + int16(int8(a[2*i+1]))
		binary.LittleEndian.PutUint16(r[2*i:], uint16(x))
	}
	return
}

//go:nosplit
func i16x8_extadd_pairwise_i8x16_u(a v128) (r v128) {
	for i := 0; i < 8; i++ {
		x := uint16(a[2*i]) + uint16(a[2*i+1])
		binary.LittleEndian.PutUint16(r[2*i:], x)
	}
	return
}

//go:nosplit
func i32x4_extadd_pairwise_i16x8_s(a v128) (r v128) {
	for i := 0; i < 4; i++ {
		x := int32(int16(binary.LittleEndian.Uint16(a[4*i:]))) + int32(int16(binary.LittleEndian.Uint16(a[4*i+2:])))
		binary.LittleEndian.PutUint32(r[4*i:], uint32(x))
	}
	return
}

//go:nosplit
func i32x4_extadd_pairwise_i16x8_u(a v128) (r v128) {
	for i := 0; i < 4; i++ {
		x := uint32(binary.LittleEndian.Uint16(a[4*i:])) + uint32(binary.LittleEndian.Uint16(a[4*i+2:]))
		binary.LittleEndian.PutUint32(r[4*i:], x)
	}
	return
}

//go:nosplit
func i16x8_extmul_low_i8x16_s(a, b v128) (r v128) {
	for i := 0; i < 8; i++ {
		x := int16(int8(a[i])) * int16(int8(b[i]))
		binary.LittleEndian.PutUint16(r[2*i:], uint16(x))
	}
	return
}

//go:nosplit
func i16x8_extmul_high_i8x16_s(a, b v128) (r v128) {
	for i := 0; i < 8; i++ {
		x := int16(int8(a[8+i])) * int16(int8(b[8+i]))
		binary.LittleEndian.PutUint16(r[2*i:], uint16(x))
	}
	return
}

//go:nosplit
func i16x8_extmul_low_i8x16_u(a, b v128) (r v128) {
	for i := 0; i < 8; i++ {
		x := uint16(a[i]) * uint16(b[i])
		binary.LittleEndian.PutUint16(r[2*i:], x)
	}
	return
}

//go:nosplit
func i16x8_extmul_high_i8x16_u(a, b v128) (r v128) {
	for i := 0; i < 8; i++ {
		x := uint16(a[8+i]) * uint16(b[8+i])
		binary.LittleEndian.PutUint16(r[2*i:], x)
	}
	return
}

//go:nosplit
func i32x4_extmul_low_i16x8_s(a, b v128) (r v128) {
	for i := 0; i < 4; i++ {
		x := int32(int16(binary.LittleEndian.Uint16(a[2*i:]))) * int32(int16(binary.LittleEndian.Uint16(b[2*i:])))
		binary.LittleEndian.PutUint32(r[4*i:], uint32(x))
	}
	return
}

//go:nosplit
func i32x4_extmul_high_i16x8_s(a, b v128) (r v128) {
	for i := 0; i < 4; i++ {
		x := int32(int16(binary.LittleEndian.Uint16(a[8+2*i:]))) * int32(int16(binary.LittleEndian.Uint16(b[8+2*i:])))
		binary.LittleEndian.PutUint32(r[4*i:], uint32(x))
	}
	return
}

//go:nosplit
func i32x4_extmul_low_i16x8_u(a, b v128) (r v128) {
	for i := 0; i < 4; i++ {
		x := uint32(binary.LittleEndian.Uint16(a[2*i:])) * uint32(binary.LittleEndian.Uint16(b[2*i:]))
		binary.LittleEndian.PutUint32(r[4*i:], x)
	}
	return
}

//go:nosplit
func i32x4_extmul_high_i16x8_u(a, b v128) (r v128) {
	for i := 0; i < 4; i++ {
		x := uint32(binary.LittleEndian.Uint16(a[8+2*i:])) * uint32(binary.LittleEndian.Uint16(b[8+2*i:]))
		binary.LittleEndian.PutUint32(r[4*i:], x)
	}
	return
}

//go:nosplit
func i64x2_extmul_low_i32x4_s(a, b v128) (r v128) {
	for i := 0; i < 2; i++ {
		x := int64(int32(binary.LittleEndian.Uint32(a[4*i:]))) * int64(int32(binary.LittleEndian.Uint32(b[4*i:])))
		binary.LittleEndian.PutUint64(r[8*i:], uint64(x))
	}
	return
}

//go:nosplit
func i64x2_extmul_high_i32x4_s(a, b v128) (r v128) {
	for i := 0; i < 2; i++ {
		x := int64(int32(binary.LittleEndian.Uint32(a[8+4*i:]))) * int64(int32(binary.LittleEndian.Uint32(b[8+4*i:])))
		binary.LittleEndian.PutUint64(r[8*i:], uint64(x))
	}
	return
}

//go:nosplit
func i64x2_extmul_low_i32x4_u(a, b v128) (r v128) {
	for i := 0; i < 2; i++ {
		x := uint64(binary.LittleEndian.Uint32(a[4*i:])) * uint64(binary.LittleEndian.Uint32(b[4*i:]))
		binary.LittleEndian.PutUint64(r[8*i:], x)
	}
	return
}

//go:nosplit
func i64x2_extmul_high_i32x4_u(a, b v128) (r v128) {
	for i := 0; i < 2; i++ {
		x := uint64(binary.LittleEndian.Uint32(a[8+4*i:])) * uint64(binary.LittleEndian.Uint32(b[8+4*i:]))
		binary.LittleEndian.PutUint64(r[8*i:], x)
	}
	return
}

//go:nosplit
func f32x4_abs(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], binary.LittleEndian.Uint32(a[i:])&0x7fffffff)
	}
	return
}

//go:nosplit
func f32x4_neg(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		binary.LittleEndian.PutUint32(r[i:], binary.LittleEndian.Uint32(a[i:])^0x80000000)
	}
	return
}

//go:nosplit
func f32x4_sqrt(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(float32(math.Sqrt(float64(x)))))
	}
	return
}

//go:nosplit
func f32x4_ceil(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(float32(math.Ceil(float64(x)))))
	}
	return
}

//go:nosplit
func f32x4_floor(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(float32(math.Floor(float64(x)))))
	}
	return
}

//go:nosplit
func f32x4_trunc(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(float32(math.Trunc(float64(x)))))
	}
	return
}

//go:nosplit
func f32x4_nearest(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(float32(math.RoundToEven(float64(x)))))
	}
	return
}

//go:nosplit
func f64x2_abs(a v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], binary.LittleEndian.Uint64(a[i:])&0x7fffffffffffffff)
	}
	return
}

//go:nosplit
func f64x2_neg(a v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		binary.LittleEndian.PutUint64(r[i:], binary.LittleEndian.Uint64(a[i:])^0x8000000000000000)
	}
	return
}

//go:nosplit
func f64x2_sqrt(a v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(math.Sqrt(x)))
	}
	return
}

//go:nosplit
func f64x2_ceil(a v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(math.Ceil(x)))
	}
	return
}

//go:nosplit
func f64x2_floor(a v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(math.Floor(x)))
	}
	return
}

//go:nosplit
func f64x2_trunc(a v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(math.Trunc(x)))
	}
	return
}

//go:nosplit
func f64x2_nearest(a v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(math.RoundToEven(x)))
	}
	return
}

//go:nosplit
func f32x4_add(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		y := math.Float32frombits(binary.LittleEndian.Uint32(b[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(x+y))
	}
	return
}

//go:nosplit
func f32x4_sub(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		y := math.Float32frombits(binary.LittleEndian.Uint32(b[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(x-y))
	}
	return
}

//go:nosplit
func f32x4_mul(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		y := math.Float32frombits(binary.LittleEndian.Uint32(b[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(x*y))
	}
	return
}

//go:nosplit
func f32x4_div(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		y := math.Float32frombits(binary.LittleEndian.Uint32(b[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(x/y))
	}
	return
}

//go:nosplit
func f64x2_add(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		y := math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(x+y))
	}
	return
}

//go:nosplit
func f64x2_sub(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		y := math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(x-y))
	}
	return
}

//go:nosplit
func f64x2_mul(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		y := math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(x*y))
	}
	return
}

//go:nosplit
func f64x2_div(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		y := math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
		binary.LittleEndian.PutUint64(r[i:], math.Float64bits(x/y))
	}
	return
}

//go:nosplit
func f32x4_min(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		y := math.Float32frombits(binary.LittleEndian.Uint32(b[i:]))
		var z uint32
		switch {
		case x != x || y != y:
			z = 0x7fc00000
		case x == y:
			z = math.Float32bits(x) | math.Float32bits(y)
		case x < y:
			z = math.Float32bits(x)
		default:
			z = math.Float32bits(y)
		}
		binary.LittleEndian.PutUint32(r[i:], z)
	}
	return
}

//go:nosplit
func f32x4_max(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		y := math.Float32frombits(binary.LittleEndian.Uint32(b[i:]))
		var z uint32
		switch {
		case x != x || y != y:
			z = 0x7fc00000
		case x == y:
			z = math.Float32bits(x) & math.Float32bits(y)
		case x > y:
			z = math.Float32bits(x)
		default:
			z = math.Float32bits(y)
		}
		binary.LittleEndian.PutUint32(r[i:], z)
	}
	return
}

//go:nosplit
func f64x2_min(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		y := math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
		var z uint64
		switch {
		case x != x || y != y:
			z = 0x7ff8000000000000
		case x == y:
			z = math.Float64bits(x) | math.Float64bits(y)
		case x < y:
			z = math.Float64bits(x)
		default:
			z = math.Float64bits(y)
		}
		binary.LittleEndian.PutUint64(r[i:], z)
	}
	return
}

//go:nosplit
func f64x2_max(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		y := math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
		var z uint64
		switch {
		case x != x || y != y:
			z = 0x7ff8000000000000
		case x == y:
			z = math.Float64bits(x) & math.Float64bits(y)
		case x > y:
			z = math.Float64bits(x)
		default:
			z = math.Float64bits(y)
		}
		binary.LittleEndian.PutUint64(r[i:], z)
	}
	return
}

//go:nosplit
func f32x4_pmin(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		y := math.Float32frombits(binary.LittleEndian.Uint32(b[i:]))
		if y < x {
			binary.LittleEndian.PutUint32(r[i:], math.Float32bits(y))
		} else {
			binary.LittleEndian.PutUint32(r[i:], math.Float32bits(x))
		}
	}
	return
}

//go:nosplit
func f32x4_pmax(a, b v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		y := math.Float32frombits(binary.LittleEndian.Uint32(b[i:]))
		if x < y {
			binary.LittleEndian.PutUint32(r[i:], math.Float32bits(y))
		} else {
			binary.LittleEndian.PutUint32(r[i:], math.Float32bits(x))
		}
	}
	return
}

//go:nosplit
func f64x2_pmin(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		y := math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
		if y < x {
			binary.LittleEndian.PutUint64(r[i:], math.Float64bits(y))
		} else {
			binary.LittleEndian.PutUint64(r[i:], math.Float64bits(x))
		}
	}
	return
}

//go:nosplit
func f64x2_pmax(a, b v128) (r v128) {
	for i := 0; i < 16; i += 8 {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[i:]))
		y := math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
		if x < y {
			binary.LittleEndian.PutUint64(r[i:], math.Float64bits(y))
		} else {
			binary.LittleEndian.PutUint64(r[i:], math.Float64bits(x))
		}
	}
	return
}

//go:nosplit
func f32x4_demote_f64x2_zero(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		x := math.Float64frombits(binary.LittleEndian.Uint64(a[8*i:]))
		binary.LittleEndian.PutUint32(r[4*i:], math.Float32bits(float32(x)))
	}
	return
}

//go:nosplit
func f64x2_promote_low_f32x4(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		x := math.Float32frombits(binary.LittleEndian.Uint32(a[4*i:]))
		binary.LittleEndian.PutUint64(r[8*i:], math.Float64bits(float64(x)))
	}
	return
}

//go:nosplit
func f32x4_convert_i32x4_s(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := int32(binary.LittleEndian.Uint32(a[i:]))
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(float32(x)))
	}
	return
}

//go:nosplit
func f32x4_convert_i32x4_u(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		x := binary.LittleEndian.Uint32(a[i:])
		binary.LittleEndian.PutUint32(r[i:], math.Float32bits(float32(x)))
	}
	return
}

//go:nosplit
func f64x2_convert_low_i32x4_s(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		x := int32(binary.LittleEndian.Uint32(a[4*i:]))
		binary.LittleEndian.PutUint64(r[8*i:], math.Float64bits(float64(x)))
	}
	return
}

//go:nosplit
func f64x2_convert_low_i32x4_u(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		x := binary.LittleEndian.Uint32(a[4*i:])
		binary.LittleEndian.PutUint64(r[8*i:], math.Float64bits(float64(x)))
	}
	return
}

//go:nosplit
func i32x4_trunc_sat_f32x4_s(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		f := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		var x int32
		switch {
		case f <= math.MinInt32:
			x = math.MinInt32
		case f >= math.MaxInt32:
			x = math.MaxInt32
		case f != f:
			x = 0
		default:
			x = int32(f)
		}
		binary.LittleEndian.PutUint32(r[i:], uint32(x))
	}
	return
}

//go:nosplit
func i32x4_trunc_sat_f32x4_u(a v128) (r v128) {
	for i := 0; i < 16; i += 4 {
		f := math.Float32frombits(binary.LittleEndian.Uint32(a[i:]))
		var x uint32
		switch {
		case f <= 0 || f != f:
			x = 0
		case f >= math.MaxUint32:
			x = math.MaxUint32
		default:
			x = uint32(f)
		}
		binary.LittleEndian.PutUint32(r[i:], x)
	}
	return
}

//go:nosplit
func i32x4_trunc_sat_f64x2_s_zero(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		f := math.Float64frombits(binary.LittleEndian.Uint64(a[8*i:]))
		var x int32
		switch {
		case f <= math.MinInt32:
			x = math.MinInt32
		case f >= math.MaxInt32:
			x = math.MaxInt32
		case f != f:
			x = 0
		default:
			x = int32(f)
		}
		binary.LittleEndian.PutUint32(r[4*i:], uint32(x))
	}
	return
}

//go:nosplit
func i32x4_trunc_sat_f64x2_u_zero(a v128) (r v128) {
	for i := 0; i < 2; i++ {
		f := math.Float64frombits(binary.LittleEndian.Uint64(a[8*i:]))
		var x uint32
		switch {
		case f <= 0 || f != f:
			x = 0
		case f >= math.MaxUint32:
			x = math.MaxUint32
		default:
			x = uint32(f)
		}
		binary.LittleEndian.PutUint32(r[4*i:], x)
	}
	return
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func load16(b []byte) uint16 {
	return binary.LittleEndian.Uint16(b)
}

//go:nosplit
func store16(b []byte, v uint16) {
	binary.LittleEndian.PutUint16(b, v)
}

//go:nosplit
func load32(b []byte) uint32 {
	return binary.LittleEndian.Uint32(b)
}

//go:nosplit
func store32(b []byte, v uint32) {
	binary.LittleEndian.PutUint32(b, v)
}

//go:nosplit
func load64(b []byte) uint64 {
	return binary.LittleEndian.Uint64(b)
}

//go:nosplit
func store64(b []byte, v uint64) {
	binary.LittleEndian.PutUint64(b, v)
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := int64(len(buf))
	old := len >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := new<<16 - len
	max = min(max, int64(math.MaxInt)>>16)
	if new > max || new < old || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
